### ISSUE TITLE
PG3 NS not working correctly.

### ISSUE THREAD

**Issue by kzboray** [jamespauly/udi-acurite-poly#2]
I have a lightning sensor and two inside temperature sensors. The node server sees the lightning sensor but does not display lightning data just the temperature and humidity. It shows one inside temperature sensor but not the other. All show up on my Acurite Dashboard. It does show up in the list of Nodes when I look in PG3 but not on my ISY... 

https://forum.universal-devices.com/topic/35956-acurite-node-server-not-seeing-all-my-sensors/#comment-338244

**Comment by jamespauly** [comment]
Thanks for that.  I just replaced my lightning sensor so let me take a look.

**Comment by jamespauly** [comment]
I pushed up a fix please test and let me know.

JP
